{% set name = "cubedsphere" %}
{% set version = "0.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cubedsphere-{{ version }}.tar.gz
  sha256: 9e5c3dd65c6ecdc159ea8abc7d3de8a1b0da3dfd343267ed6e452f9d9e828d8b

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - esmpy
    - matplotlib-base
    - numpy
    - python >=3.6
    - xesmf
    - xgcm
    - xmitgcm
    - xarray

test:
  imports:
    - cubedsphere
    - cubedsphere.exorad
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/AaronDavidSchneider/cubedsphere
  summary: Library for post processing of MITgcm cubed sphere data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AaronDavidSchneider
